services:
  app:
    build:
      context: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - huggingface_cache:/app/.cache/huggingface
    command: uv run streamlit run src/app/streamlit_app.py

  index:
    build:
      context: .
    profiles:
      - index
    volumes:
      - ./data:/app/data
      - huggingface_cache:/app/.cache/huggingface
    command: uv run python -m src.pipeline.run_pipeline --rebuild-index

  pipeline:
    build:
      context: .
    profiles:
      - pipeline
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - huggingface_cache:/app/.cache/huggingface
    command: uv run python -m src.pipeline.run_pipeline --run-llm --rebuild-index

volumes:
  huggingface_cache:
